#!/bin/bash

# This is a thin wrapper around sunlightcoin-cli that strips the Windows-style EOLs
# from the output if present. It is necessary when using sunlightcoin-cli.exe on
# Linux since shells will interpret the line-endings as part of the result.

CURDIR=$(cd $(dirname "$0"); pwd)
# Get BUILDDIR and REAL_SUNLIGHTCOIND

# Grab the value of $REAL_SUNLIGHTCOINCLI which may be sunlightcoin-cli.exe.
. "${CURDIR}/tests-config.sh"

"${REAL_SUNLIGHTCOINCLI}" "$@" | sed 's/\r//'
